version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

executors:
  tt-executor:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/typetastic

jobs:
  build:
    executor: tt-executor
    steps:
      - checkout

      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make dev
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
          paths:
            - "venv"

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test

  deploy:
    executor: tt-executor
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make dev
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
          paths:
            - "venv"
      - run:
          name: verify git tag vs. version
          command: |
            . venv/bin/activate
            python setup.py verify
      - run:
          name: add password to .pypirc
          command: |
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: build deployment packages
          command: |
            make build
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            python3 -m twine upload -r testpypi --config-file ~/.pypirc  dist/*
